# Generated by Django 5.2.1 on 2025-06-17 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_kid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.DeleteModel(
            name='kid',
        ),
    ]
